### ISSUE TITLE
After updating os version to 9 application crash. Please refer crash log in description.

### ISSUE THREAD

**Issue by akashMehta-STL** [zuoweitan/CircleImageView#4]
Fatal Exception: java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
       at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
       at android.graphics.Canvas.saveLayer(Canvas.java:455)
       at com.zuowei.circleimageview.CircleImageView.onDraw(CircleImageView.java:137)
       at android.view.View.draw(View.java:20366)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1888)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at com.android.internal.policy.DecorView.draw(DecorView.java:781)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3515)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3312)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2681)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7786)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
       at android.view.Choreographer.doCallbacks(Choreographer.java:816)
       at android.view.Choreographer.doFrame(Choreographer.java:751)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ChinaFLTV** [comment]
+1
